name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set lower case
        run: |
          echo "REPO_LC=${REPO_LC,,}" >>${GITHUB_ENV}
        env:
          REPO_LC: ${{ github.repository }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push the Docker image to the container registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{env.REPO_LC}}:${{github.sha}}
          secrets: |
            DOCKER_TOKEN=${{secrets.DOCKER_TOKEN}}
            # GIT_AUTH_TOKEN=${{secrets.GIT_TOKEN}}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set lower case
        run: |
          echo "REPO_LC=${REPO_LC,,}" >>${GITHUB_ENV}
        env:
          REPO_LC: ${{ github.repository }}
      - name: Deploy to server with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Deploying to server..."
            docker pull ghcr.io/${{env.REPO_LC}}:${{github.sha}}
            cd ${{ vars.COMPOSE_DIR }}
            echo "Compose up to server..."
            sed -i "s/image: .*/image: ghcr.io/${{env.REPO_LC}}:${{github.sha}}" docker-compose.yml
            docker-compose up -d
